services:
  sevpn:
    build:
      context: sevpn/.
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volume_data/softether_data:/mnt"
      - "./volume_data/softether_log:/usr/local/bin/server_log"
      - "./volume_data/softether_packetlog:/usr/local/bin/packet_log"
      - "./volume_data/softether_securitylog:/usr/local/bin/security_log"
    privileged: true
    environment:
      VPN_DOMAIN: ${VPN_DOMAIN}
