name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-docker: ${{ steps.release.outputs['docker--release_created'] }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@v4
        id: release
  release-docker:
    needs: release-please
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.release-please.outputs.release-docker
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.tag }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push (server)
        uses: docker/build-push-action@v6
        with:
          context: server-sevpn
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/server-sevpn:latest
            ghcr.io/${{ github.repository_owner }}/server-sevpn:${{ steps.vars.outputs.tag  }}
      - name: Build and push (client)
        uses: docker/build-push-action@v6
        with:
          context: client-sevpn
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/client-sevpn:latest
            ghcr.io/${{ github.repository_owner }}/client-sevpn:${{ steps.vars.outputs.tag  }}
